#! /bin/bash

REPOSITORY_DIR=/home/nielx/haiku-repository
CATALOG_DIR=%(project_path)s/catalogs/haiku
IMPORT_SCRIPT_PATH=%(project_path)s/scripts/import_templates_from_haiku-files.py
FINISH_SCRIPT_PATH=%(project_path)s/scripts/finish_output_catalogs.py
POOTLE_MANAGE_SCRIPT_PATH=%(project_path)s/pootle-svn/manage.py

check_errors()
{
  # Function. Parameter 1 is the return code
  # Para. 2 is text to display on failure.
  if [ "${1}" -ne "0" ]; then
    echo "ERROR # ${1} : ${2}"
    # as a bonus, make our script exit with the right error code.
    exit ${1}
  fi
}

cd $REPOSITORY_DIR
sudo -u wwwrun python $IMPORT_SCRIPT_PATH $CATALOG_DIR
check_errors $? "Error importing the new translations from the build factory"
sudo -u wwwrun python $POOTLE_MANAGE_SCRIPT_PATH update_stores --language=en 
check_errors $? "Error updating the English language catalogs"
sudo -u wwwrun python $POOTLE_MANAGE_SCRIPT_PATH update_from_templates
check_errors $? "Error updating the language translations from the English templates"
sudo -u wwwrun python $POOTLE_MANAGE_SCRIPT_PATH sync_stores
check_errors $? "Error writing the updated translations to files"
sudo chmod -R a+r $CATALOG_DIR/* 
check_errors $? "Error performing a chmod operation"
sudo -u nielx python $FINISH_SCRIPT_PATH $CATALOG_DIR $REPOSITORY_DIR/data/catalogs/
check_errors $? "Error copying the updated translations to the git tree"
sudo -u nielx git add -A
sudo -u nielx git commit -m "Update translations from Pootle"
check_errors $? "Git Error: Error committing the changes to the repository"
sudo -u nielx git pull --rebase
check_errors $? "Git Error: Error pulling the latest revisions into the repository"
sudo -u nielx git push
check_errors $? "Git Error: Error pushing the translations to the Haiku repository"
