#! /bin/bash

REPOSITORY_DIR=/home/nielx/haiku-repository
CATALOG_DIR=%(project_path)s/catalogs/haiku
IMPORT_SCRIPT_PATH=%(project_path)s/scripts/import_templates_from_haiku-files.py
FINISH_SCRIPT_PATH=%(project_path)s/scripts/finish_output_catalogs.py
POOTLE_COMMAND_PATH=%(project_path)s/env/bin/pootle
POOTLE_CONFIGURATION_PATH=%(project_path)s/settings/90-local.conf
POT2PO_COMMAND_PATH=%(project_path)s/env/bin/pot2po
PYTHON_EXECUTABLE=%(project_path)s/env/bin/python


check_errors()
{
  # Function. Parameter 1 is the return code
  # Para. 2 is text to display on failure.
  if [ "${1}" -ne "0" ]; then
    echo "ERROR # ${1} : ${2}"
    # as a bonus, make our script exit with the right error code.
    exit ${1}
  fi
}

cd $REPOSITORY_DIR

# 1 sync database to disk
sudo -u wwwrun $POOTLE_COMMAND_PATH --config $POOTLE_CONFIGURATION_PATH sync_stores
check_errors $? "Error writing the current catalogs to disk"

# 2 download templates and merge
sudo -u wwwrun $PYTHON_EXECUTABLE $IMPORT_SCRIPT_PATH --pot2po $POT2PO_COMMAND_PATH $CATALOG_DIR
check_errors $? "Error importing the new translations from the build factory and merging them to the translated files"

# 3 load the translated files into Pootle
sudo -u wwwrun $POOTLE_COMMAND_PATH --config $POOTLE_CONFIGURATION_PATH update_stores
check_errors $? "Error importing the catalogs into pootle"

# 4 export the translated files to git
sudo chmod -R a+r $CATALOG_DIR/*
check_errors $? "Error performing a chmod operation"
sudo -u nielx $PYTHON_EXECUTABLE $FINISH_SCRIPT_PATH $CATALOG_DIR $REPOSITORY_DIR/data/catalogs/
check_errors $? "Error copying the updated translations to the git tree"
sudo -u nielx git add -A
sudo -u nielx git commit -m "Update translations from Pootle"
check_errors $? "Git Error: Error committing the changes to the repository"
sudo -u nielx git pull --rebase
check_errors $? "Git Error: Error pulling the latest revisions into the repository"
sudo -u nielx git push
check_errors $? "Git Error: Error pushing the translations to the Haiku repository"
